import type {
  AccountDetail,
  CaseFile,
  CommunicationReport,
  ModelMetrics,
  NetworkLink,
  NetworkNode,
  SuspiciousAccount,
  SuspiciousTransaction,
} from './types';

export const mockTransactions: SuspiciousTransaction[] = [
  // Rantai Transaksi Pencucian Uang (4 hop) - ILLEGAL MINING
  {
    id: 'TXN-CHAIN-A',
    timestamp: '2024-05-22T08:00:00Z',
    amount: 500000000,
    currency: 'IDR',
    source: {
      id: 'ACC-MINING-CO',
      name: 'PT Tambang Ilegal',
      bank: 'Bank F',
      country: 'IDN',
      type: 'Company',
    },
    destination: {
      id: 'ACC-LAWYER-A',
      name: 'Law Firm ABC',
      bank: 'Bank E',
      country: 'IDN',
      type: 'Company',
    },
    riskScore: 85,
    category: 'Illegal Mining',
    reason: 'Initial placement from high-risk mining company to a legal firm.',
    status: 'Blocked',
    channel: 'SWIFT',
    device: { id: 'DEV-CHAIN', ip: '202.1.2.3', location: 'Kalimantan, ID' },
  },
  {
    id: 'TXN-CHAIN-B',
    timestamp: '2024-05-22T08:30:00Z',
    amount: 495000000,
    currency: 'IDR',
    source: {
      id: 'ACC-LAWYER-A',
      name: 'Law Firm ABC',
      bank: 'Bank E',
      country: 'IDN',
      type: 'Company',
    },
    destination: {
      id: 'ACC-PROPERTY-DEV',
      name: 'Properti Megah Corp',
      bank: 'Bank G',
      country: 'IDN',
      type: 'Company',
    },
    riskScore: 88,
    category: 'Illegal Mining',
    reason: 'Layering: Funds moved from legal firm to property developer.',
    status: 'Blocked',
    channel: 'SWIFT',
    device: { id: 'DEV-CHAIN', ip: '103.5.6.7', location: 'Jakarta, ID' },
    previousTxId: 'TXN-CHAIN-A',
  },
  {
    id: 'TXN-CHAIN-C',
    timestamp: '2024-05-22T09:00:00Z',
    amount: 490000000,
    currency: 'IDR',
    source: {
      id: 'ACC-PROPERTY-DEV',
      name: 'Properti Megah Corp',
      bank: 'Bank G',
      country: 'IDN',
      type: 'Company',
    },
    destination: {
      id: 'ACC-SHELL-CYM',
      name: 'Verdant Holdings Ltd.',
      bank: 'Global Trust Bank',
      country: 'CYM',
      type: 'Company',
    },
    riskScore: 96,
    category: 'Illegal Mining',
    reason: 'Layering: Funds moved to offshore shell company.',
    status: 'Blocked',
    channel: 'SWIFT',
    device: { id: 'DEV-CHAIN', ip: '103.5.6.7', location: 'Jakarta, ID' },
    previousTxId: 'TXN-CHAIN-B',
  },
  {
    id: 'TXN-CHAIN-D',
    timestamp: '2024-05-22T10:00:00Z',
    amount: 30000,
    currency: 'USD',
    source: {
      id: 'ACC-SHELL-CYM',
      name: 'Verdant Holdings Ltd.',
      bank: 'Global Trust Bank',
      country: 'CYM',
      type: 'Company',
    },
    destination: {
      id: 'ACC-POL-Z',
      name: 'Politician Z',
      bank: 'Bank C',
      country: 'IDN',
      type: 'Individual',
    },
    riskScore: 99,
    category: 'Illegal Mining',
    reason: 'Integration: Payment to Politically Exposed Person (PEP).',
    status: 'Blocked',
    channel: 'SWIFT',
    device: { id: 'DEV-OFFSHORE', ip: '5.5.5.5', location: 'Cayman Islands' },
    previousTxId: 'TXN-CHAIN-C',
  },

  // Transaksi Tunggal
  {
    id: 'TXN-GFC-001',
    timestamp: '2024-05-21T10:30:00Z',
    amount: 1500000000,
    currency: 'IDR',
    source: {
      id: 'ACC-PT-KAYU',
      name: 'PT Kayu Makmur Abadi',
      bank: 'Bank A',
      country: 'IDN',
      type: 'Company',
    },
    destination: {
      id: 'ACC-SHELL-CYM',
      name: 'Verdant Holdings Ltd.',
      bank: 'Global Trust Bank',
      country: 'CYM',
      type: 'Company',
    },
    riskScore: 95,
    category: 'Illegal Logging',
    reason:
      'Large transfer to offshore high-risk jurisdiction from forestry sector.',
    status: 'Blocked',
    channel: 'SWIFT',
    device: { id: 'DEV-001', ip: '103.45.1.2', location: 'Jakarta, ID' },
  },
  {
    id: 'TXN-GFC-002',
    timestamp: '2024-05-21T09:15:00Z',
    amount: 50000000,
    currency: 'IDR',
    source: {
      id: 'ACC-INDIV-X',
      name: 'Bambang S.',
      bank: 'Bank B',
      country: 'IDN',
      type: 'Individual',
    },
    destination: {
      id: 'ACC-POL-Z',
      name: 'Politician Z',
      bank: 'Bank C',
      country: 'IDN',
      type: 'Individual',
    },
    riskScore: 88,
    category: 'Illegal Mining',
    reason:
      'Structuring: 5 transactions of 10M in 1 hour from an account in a known illegal mining area.',
    status: 'Under Review',
    channel: 'Mobile Banking',
    device: { id: 'DEV-002', ip: '202.150.3.4', location: 'Pontianak, ID' },
  },
  {
    id: 'TXN-GFC-003',
    timestamp: '2024-05-20T22:00:00Z',
    amount: 15000,
    currency: 'USD',
    source: {
      id: 'ACC-NGO-FUND',
      name: 'Global Nature Fund',
      bank: 'Citibank',
      country: 'USA',
      type: 'Company',
    },
    destination: {
      id: 'ACC-WILDLIFE-EXP',
      name: 'Exotic Fauna Global',
      bank: 'Vietcombank',
      country: 'VNM',
      type: 'Company',
    },
    riskScore: 98,
    category: 'Wildlife Trafficking',
    reason:
      'Transaction pattern matches known wildlife trafficking financing typology.',
    status: 'Blocked',
    channel: 'SWIFT',
    device: { id: 'DEV-003', ip: '1.55.2.3', location: 'Hanoi, VN' },
  },
  {
    id: 'TXN-GFC-004',
    timestamp: '2024-05-20T14:00:00Z',
    amount: 50000,
    currency: 'EUR',
    source: {
      id: 'ACC-WASTE-EU',
      name: 'Euro Recycle GmbH',
      bank: 'Deutsche Bank',
      country: 'DEU',
      type: 'Company',
    },
    destination: {
      id: 'ACC-PORT-INA',
      name: 'PT Pelabuhan Nusantara',
      bank: 'Bank A',
      country: 'IDN',
      type: 'Company',
    },
    riskScore: 82,
    category: 'Waste Trade',
    reason: 'Payment for waste import from a company with previous sanctions.',
    status: 'Flagged',
    channel: 'SWIFT',
    device: { id: 'DEV-004', ip: '88.1.2.3', location: 'Hamburg, DE' },
  },
  {
    id: 'TXN-GFC-005',
    timestamp: '2024-05-19T11:00:00Z',
    amount: 200000000,
    currency: 'SGD',
    source: {
      id: 'ACC-CARBON-A',
      name: 'Green Credits Asia',
      bank: 'DBS',
      country: 'SGP',
      type: 'Company',
    },
    destination: {
      id: 'ACC-CARBON-B',
      name: 'Eco Projects Indonesia',
      bank: 'Bank B',
      country: 'IDN',
      type: 'Company',
    },
    riskScore: 91,
    category: 'Carbon Credit Fraud',
    reason:
      'Anomalous high-volume trading of carbon credits with circular fund flows.',
    status: 'Flagged',
    channel: 'Online',
    device: { id: 'DEV-005', ip: '118.100.1.2', location: 'Singapore, SG' },
  },
  ...Array.from({ length: 20 }, (_, i) => ({
    id: `TXN-GFC-0${i + 10}`,
    timestamp: new Date(Date.now() - i * 3600000).toISOString(),
    amount: Math.floor(Math.random() * 1e9) + 1e7,
    currency: 'IDR' as const,
    source: {
      id: `ACC-SRC-${i}`,
      name: `Source Corp ${i}`,
      bank: 'Bank D',
      country: 'IDN',
      type: 'Company' as const,
    },
    destination: {
      id: `ACC-DST-${i}`,
      name: `Offshore Ltd ${i}`,
      bank: 'International Bank',
      country: 'HKG',
      type: 'Company' as const,
    },
    riskScore: Math.floor(Math.random() * 40) + 60,
    category: 'Illegal Logging' as const,
    reason: 'Automated generation for testing.',
    status: 'Flagged' as const,
    channel: 'Online' as const,
    device: { id: `DEV-RAND-${i}`, ip: '127.0.0.1', location: 'Unknown' },
  })),
];

export const mockAccounts: SuspiciousAccount[] = [
  {
    id: 'ACC-PT-KAYU',
    name: 'PT Kayu Makmur Abadi',
    bank: 'Bank A',
    riskScore: 95,
    status: 'Suspicious',
    balance: 25000000000,
    currency: 'IDR',
    transactionCount: { incoming: 5, outgoing: 7 },
    lastActivity: '2024-05-21',
    type: 'Company',
    kycLevel: 'Incomplete',
    openDate: '2022-01-15',
  },
  {
    id: 'ACC-SHELL-CYM',
    name: 'Verdant Holdings Ltd.',
    bank: 'Global Trust Bank',
    riskScore: 99,
    status: 'Suspicious',
    balance: 95000,
    currency: 'USD',
    transactionCount: { incoming: 2, outgoing: 1 },
    lastActivity: '2024-05-22',
    type: 'Company',
    kycLevel: 'Incomplete',
    openDate: '2024-05-20',
  },
  {
    id: 'ACC-WILDLIFE-EXP',
    name: 'Exotic Fauna Global',
    bank: 'Vietcombank',
    riskScore: 98,
    status: 'Blocked',
    balance: 50000000,
    currency: 'IDR',
    transactionCount: { incoming: 20, outgoing: 5 },
    lastActivity: '2024-05-20',
    type: 'Company',
    kycLevel: 'Basic',
    openDate: '2023-08-10',
  },
  {
    id: 'ACC-INDIV-X',
    name: 'Bambang S.',
    bank: 'Bank B',
    riskScore: 88,
    status: 'Frozen',
    balance: 120000000,
    currency: 'IDR',
    transactionCount: { incoming: 10, outgoing: 20 },
    lastActivity: '2024-05-21',
    type: 'Individual',
    kycLevel: 'Enhanced',
    openDate: '2021-03-20',
  },
  {
    id: 'ACC-POL-Z',
    name: 'Politician Z',
    bank: 'Bank C',
    riskScore: 85,
    status: 'Suspicious',
    balance: 5000000000,
    currency: 'IDR',
    transactionCount: { incoming: 30, outgoing: 2 },
    lastActivity: '2024-05-22',
    type: 'Individual',
    kycLevel: 'Enhanced',
    openDate: '2020-01-01',
  },
  {
    id: 'ACC-LAWYER-A',
    name: 'Law Firm ABC',
    bank: 'Bank E',
    riskScore: 75,
    status: 'Active',
    balance: 12000000000,
    currency: 'IDR',
    transactionCount: { incoming: 50, outgoing: 45 },
    lastActivity: '2024-05-22',
    type: 'Company',
    kycLevel: 'Enhanced',
    openDate: '2019-06-01',
  },
  {
    id: 'ACC-MINING-CO',
    name: 'PT Tambang Ilegal',
    bank: 'Bank F',
    riskScore: 96,
    status: 'Blocked',
    balance: 5000000,
    currency: 'IDR',
    transactionCount: { incoming: 2, outgoing: 15 },
    lastActivity: '2024-05-22',
    type: 'Company',
    kycLevel: 'Incomplete',
    openDate: '2023-11-05',
  },
  {
    id: 'ACC-PROPERTY-DEV',
    name: 'Properti Megah Corp',
    bank: 'Bank G',
    riskScore: 78,
    status: 'Active',
    balance: 150000000000,
    currency: 'IDR',
    transactionCount: { incoming: 100, outgoing: 95 },
    lastActivity: '2024-05-22',
    type: 'Company',
    kycLevel: 'Enhanced',
    openDate: '2018-02-14',
  },
  ...Array.from({ length: 15 }, (_, i) => ({
    id: `ACC-SUS-${i}`,
    name: `Suspicious Entity ${i + 1}`,
    bank: 'Bank C',
    riskScore: Math.floor(Math.random() * 30) + 70,
    status: 'Suspicious' as const,
    balance: Math.random() * 1e10,
    currency: 'IDR' as const,
    transactionCount: {
      incoming: Math.floor(Math.random() * 25),
      outgoing: Math.floor(Math.random() * 25),
    },
    lastActivity: new Date(Date.now() - i * 86400000)
      .toISOString()
      .split('T')[0],
    type: 'Company' as const,
    kycLevel: 'Basic',
    openDate: '2023-01-01',
  })),
].sort((a, b) => b.riskScore - a.riskScore);

export const mockCaseFiles: CaseFile[] = [
  {
    id: 'CASE-2024-052',
    title: 'Illegal Mining Money Laundering Chain',
    priority: 'Critical',
    status: 'New',
    investigator: 'Unassigned',
    createdDate: '2024-05-22',
    lastUpdate: '2024-05-22',
    summary:
      'A complex 4-hop transaction chain originating from an illegal mining operation, moving funds through a law firm, property developer, and finally to an offshore account linked to a PEP.',
    potentialLoss: 500000000,
    threatActors: ['Politician Z', 'PT Tambang Ilegal'],
    relatedTransactions: [
      'TXN-CHAIN-A',
      'TXN-CHAIN-B',
      'TXN-CHAIN-C',
      'TXN-CHAIN-D',
    ],
    relatedAccounts: [
      'ACC-MINING-CO',
      'ACC-LAWYER-A',
      'ACC-PROPERTY-DEV',
      'ACC-SHELL-CYM',
      'ACC-POL-Z',
    ],
    evidence: [],
    log: [],
  },
  {
    id: 'CASE-2024-051',
    title: 'PT Kayu Gelap Export Ring',
    priority: 'Critical',
    status: 'Investigating',
    investigator: 'Team Alpha',
    createdDate: '2024-05-15',
    lastUpdate: '2024-05-21',
    summary:
      'Investigation into a suspected illegal logging operation using a complex network of shell companies to launder proceeds.',
    potentialLoss: 1500000000,
    threatActors: ['Bambang S.', 'Politician Z'],
    relatedTransactions: ['TXN-GFC-001'],
    relatedAccounts: ['ACC-PT-KAYU', 'ACC-SHELL-CYM'],
    evidence: [
      {
        id: 'EV-001',
        name: 'STR_Report_BankA.pdf',
        type: 'STR',
        uploadedAt: '2024-05-15',
      },
    ],
    log: [
      {
        timestamp: '2024-05-21',
        user: 'Regulator A',
        action: 'Escalated to OJK',
        notes: 'Requesting transaction freeze on related accounts.',
      },
    ],
  },
  {
    id: 'CASE-2024-050',
    title: 'Sumatran Tiger Trafficking Network',
    priority: 'High',
    status: 'Pending Review',
    investigator: 'Team Bravo',
    createdDate: '2024-04-28',
    lastUpdate: '2024-05-19',
    summary:
      'A network of individuals involved in the trafficking of protected wildlife, using crypto and fintech for payments.',
    potentialLoss: 250000000,
    threatActors: ['Unknown Syndicate'],
    relatedTransactions: ['TXN-GFC-003'],
    relatedAccounts: ['ACC-WILDLIFE-EXP'],
    evidence: [
      {
        id: 'EV-002',
        name: 'Crypto_Wallet_Trace.png',
        type: 'Image',
        uploadedAt: '2024-05-18',
      },
    ],
    log: [
      {
        timestamp: '2024-05-19',
        user: 'Regulator B',
        action: 'Pending review by supervisor',
        notes: 'All evidence collected. Awaiting approval for next steps.',
      },
    ],
  },
];

export const mockModelMetrics: ModelMetrics = {
  accuracy: 99.7,
  precision: 98.2,
  recall: 97.5,
  f1Score: 97.8,
  auc: 0.99,
  modelVersion: 'GFC-Det v3.1',
  lastTrained: '2024-05-01',
  featureImportance: [
    { feature: 'Transaction to High-Risk Jurisdiction', importance: 0.25 },
    { feature: 'Transaction Structuring Pattern', importance: 0.2 },
    { feature: 'Sender/Receiver in Watchlist', importance: 0.18 },
    { feature: 'Anomalous Transaction Volume', importance: 0.15 },
    { feature: 'Use of Shell Corporations', importance: 0.12 },
    { feature: 'Connection to PEP', importance: 0.1 },
  ],
  performanceOverTime: [
    { date: 'Jan', accuracy: 99.5, precision: 97.8 },
    { date: 'Feb', accuracy: 99.6, precision: 98.0 },
    { date: 'Mar', accuracy: 99.6, precision: 98.1 },
    { date: 'Apr', accuracy: 99.7, precision: 98.2 },
  ],
};

export const mockNetworkNodes: NetworkNode[] = [
  {
    id: 'ACC-PT-KAYU',
    name: 'PT Kayu Makmur Abadi',
    type: 'Company',
    riskScore: 95,
  },
  {
    id: 'ACC-SHELL-CYM',
    name: 'Verdant Holdings Ltd.',
    type: 'Offshore',
    riskScore: 99,
  },
  {
    id: 'ACC-WILDLIFE-EXP',
    name: 'Exotic Fauna Global',
    type: 'Company',
    riskScore: 98,
  },
  { id: 'ACC-INDIV-X', name: 'Bambang S.', type: 'Individual', riskScore: 88 },
  { id: 'ACC-POL-Z', name: 'Politician Z', type: 'Individual', riskScore: 85 },
  { id: 'ACC-LAWYER-A', name: 'Law Firm ABC', type: 'Company', riskScore: 75 },
  {
    id: 'ACC-MINING-CO',
    name: 'PT Tambang Ilegal',
    type: 'Company',
    riskScore: 96,
  },
  {
    id: 'ACC-PROPERTY-DEV',
    name: 'Properti Megah Corp',
    type: 'Company',
    riskScore: 78,
  },
];

export const mockNetworkLinks: NetworkLink[] = [
  { source: 'ACC-PT-KAYU', target: 'ACC-SHELL-CYM' },
  { source: 'ACC-INDIV-X', target: 'ACC-PT-KAYU' },
  { source: 'ACC-PT-KAYU', target: 'ACC-POL-Z' },
  { source: 'ACC-WILDLIFE-EXP', target: 'ACC-SHELL-CYM' },
  { source: 'ACC-POL-Z', target: 'ACC-LAWYER-A' },
  { source: 'ACC-MINING-CO', target: 'ACC-LAWYER-A' },
  { source: 'ACC-LAWYER-A', target: 'ACC-PROPERTY-DEV' },
  { source: 'ACC-PROPERTY-DEV', target: 'ACC-SHELL-CYM' },
];

export const mockCommunicationReports: CommunicationReport[] = [
  {
    id: 'REP-001',
    date: '2024-05-21',
    relatedCase: 'CASE-2024-051',
    institution: 'Bank Mandiri',
    subject: 'Request for Account Freezing - ACC-PT-KAYU',
    status: 'Sent',
  },
  {
    id: 'REP-002',
    date: '2024-05-20',
    relatedCase: 'CASE-2024-051',
    institution: 'OJK',
    subject: 'Suspicious Activity Report - PT Kayu Makmur Abadi',
    status: 'Acknowledged',
  },
];

export const mockAccountDetails: AccountDetail[] = mockAccounts.map(acc => ({
  ...acc,
  address: 'Jl. Jenderal Sudirman No. 52, Jakarta, Indonesia',
  country: acc.id.includes('CYM') ? 'Cayman Islands' : 'Indonesia',
  firstSeen: acc.openDate,
  linkedEntities: [
    { id: 'DEV-98765', type: 'Device', relationship: 'Primary Device' },
    { id: '103.45.67.89', type: 'IP', relationship: 'Frequent IP' },
    ...(acc.riskScore > 90
      ? [
          {
            id: 'ACC-SHELL-CYM',
            type: 'Related Account' as const,
            relationship: 'Transferred Funds To',
          },
        ]
      : []),
  ],
  transactions: mockTransactions.filter(
    tx => tx.source.id === acc.id || tx.destination.id === acc.id
  ),
}));
